#pragma once

enum ECstrike15UserMessages
{
    CS_UM_VGUIMenu = 1,
    CS_UM_Geiger = 2,
    CS_UM_Train = 3,
    CS_UM_HudText = 4,
    CS_UM_SayText = 5,
    CS_UM_SayText2 = 6,
    CS_UM_TextMsg = 7,
    CS_UM_HudMsg = 8,
    CS_UM_ResetHud = 9,
    CS_UM_GameTitle = 10,
    CS_UM_Shake = 12,
    CS_UM_Fade = 13,
    CS_UM_Rumble = 14,
    CS_UM_CloseCaption = 15,
    CS_UM_CloseCaptionDirect = 16,
    CS_UM_SendAudio = 17,
    CS_UM_RawAudio = 18,
    CS_UM_VoiceMask = 19,
    CS_UM_RequestState = 20,
    CS_UM_Damage = 21,
    CS_UM_RadioText = 22,
    CS_UM_HintText = 23,
    CS_UM_KeyHintText = 24,
    CS_UM_ProcessSpottedEntityUpdate = 25,
    CS_UM_ReloadEffect = 26,
    CS_UM_AdjustMoney = 27,
    CS_UM_UpdateTeamMoney = 28,
    CS_UM_StopSpectatorMode = 29,
    CS_UM_KillCam = 30,
    CS_UM_DesiredTimescale = 31,
    CS_UM_CurrentTimescale = 32,
    CS_UM_AchievementEvent = 33,
    CS_UM_MatchEndConditions = 34,
    CS_UM_DisconnectToLobby = 35,
    CS_UM_PlayerStatsUpdate = 36,
    CS_UM_DisplayInventory = 37,
    CS_UM_WarmupHasEnded = 38,
    CS_UM_ClientInfo = 39,
    CS_UM_XRankGet = 40,
    CS_UM_XRankUpd = 41,
    CS_UM_CallVoteFailed = 45,
    CS_UM_VoteStart = 46,
    CS_UM_VotePass = 47,
    CS_UM_VoteFailed = 48,
    CS_UM_VoteSetup = 49,
    CS_UM_ServerRankRevealAll = 50,
    CS_UM_SendLastKillerDamageToClient = 51,
    CS_UM_ServerRankUpdate = 52,
    CS_UM_ItemPickup = 53,
    CS_UM_ShowMenu = 54,
    CS_UM_BarTime = 55,
    CS_UM_AmmoDenied = 56,
    CS_UM_MarkAchievement = 57,
    CS_UM_MatchStatsUpdate = 58,
    CS_UM_ItemDrop = 59,
    CS_UM_GlowPropTurnOff = 60,
    CS_UM_SendPlayerItemDrops = 61,
    CS_UM_RoundBackupFilenames = 62,
    CS_UM_SendPlayerItemFound = 63,
    CS_UM_ReportHit = 64,
    CS_UM_XpUpdate = 65,
    CS_UM_QuestProgress = 66,
    CS_UM_ScoreLeaderboardData = 67,
    CS_UM_PlayerDecalDigitalSignature = 68
};


enum ItemDefinitionIndex
{
    ITEM_NONE = 0,
    WEAPON_DEAGLE = 1,
    WEAPON_DUALS = 2,
    WEAPON_FIVE7 = 3,
    WEAPON_GLOCK = 4,
    WEAPON_AK47 = 7,
    WEAPON_AUG = 8,
    WEAPON_AWP = 9,
    WEAPON_FAMAS = 10,
    WEAPON_G3SG1 = 11,
    WEAPON_GALIL = 13,
    WEAPON_M249 = 14,
    WEAPON_M4A1 = 16,
    WEAPON_MAC10 = 17,
    WEAPON_P90 = 19,
    WEAPON_UMP45 = 24,
    WEAPON_XM1014 = 25,
    WEAPON_BIZON = 26,
    WEAPON_MAG7 = 27,
    WEAPON_NEGEV = 28,
    WEAPON_SAWEDOFF = 29,
    WEAPON_TEC9 = 30,
    WEAPON_TASER = 31,
    WEAPON_P2000 = 32,
    WEAPON_MP7 = 33,
    WEAPON_MP9 = 34,
    WEAPON_NOVA = 35,
    WEAPON_P250 = 36,
    WEAPON_SCAR20 = 38,
    WEAPON_SG553 = 39,
    WEAPON_SCOUT = 40,
    WEAPON_KNIFE_T = 42,
    WEAPON_FLASH = 43,
    WEAPON_HE = 44,
    WEAPON_SMOKE = 45,
    WEAPON_MOLOTOV = 46,
    WEAPON_DECOY = 47,
    WEAPON_INC = 48,
    WEAPON_C4 = 49,
    WEAPON_KNIFE_CT = 59,
    WEAPON_M4A1S = 60,
    WEAPON_USPS = 61,
    WEAPON_CZ75 = 63,
    WEAPON_REVOLVER = 64,
    WEAPON_KNIFE_BAYONET = 500,
    WEAPON_KNIFE_FLIP = 505,
    WEAPON_KNIFE_GUT = 506,
    WEAPON_KNIFE_KARAMBIT = 507,
    WEAPON_KNIFE_M9BAYONET = 508,
    WEAPON_KNIFE_HUNTSMAN = 509,
    WEAPON_KNIFE_FALCHION = 512,
    WEAPON_KNIFE_BOWIE = 514,
    WEAPON_KNIFE_BUTTERFLY = 515,
    WEAPON_KNIFE_DAGGER = 516,
    WEAPON_MAX
};

enum ClassId
{
    CAK47 = 1,
    CBaseAnimating = 2,
    CBaseAnimatingOverlay = 3,
    CBaseAttributableItem = 4,
    CBaseButton = 5,
    CBaseCombatCharacter = 6,
    CBaseCombatWeapon = 7,
    CBaseCSGrenade = 8,
    CBaseCSGrenadeProjectile = 9,
    CBaseDoor = 10,
    CBaseEntity = 11,
    CBaseFlex = 12,
    CBaseGrenade = 13,
    CBaseParticleEntity = 14,
    CBasePlayer = 15,
    CBasePropDoor = 16,
    CBaseTeamObjectiveResource = 17,
    CBaseTempEntity = 18,
    CBaseToggle = 19,
    CBaseTrigger = 20,
    CBaseViewModel = 21,
    CBaseVPhysicsTrigger = 22,
    CBaseWeaponWorldModel = 23,
    CBeam = 24,
    CBeamSpotlight = 25,
    CBoneFollower = 26,
    CBreakableProp = 27,
    CBreakableSurface = 28,
    CC4 = 29,
    CCascadeLight = 30,
    CChicken = 31,
    CColorCorrection = 32,
    CColorCorrectionVolume = 33,
    CCSGameRulesProxy = 34,
    CCSPlayer = 35,
    CCSPlayerResource = 36,
    CCSRagdoll = 37,
    CCSTeam = 38,
    CDEagle = 39,
    CDecoyGrenade = 40,
    CDecoyProjectile = 41,
    CDynamicLight = 42,
    CDynamicProp = 43,
    CEconEntity = 44,
    CEconWearable = 45,
    CEmbers = 46,
    CEntityDissolve = 47,
    CEntityFlame = 48,
    CEntityFreezing = 49,
    CEntityParticleTrail = 50,
    CEnvAmbientLight = 51,
    CEnvDetailController = 52,
    CEnvDOFController = 53,
    CEnvParticleScript = 54,
    CEnvProjectedTexture = 55,
    CEnvQuadraticBeam = 56,
    CEnvScreenEffect = 57,
    CEnvScreenOverlay = 58,
    CEnvTonemapController = 59,
    CEnvWind = 60,
    CFEPlayerDecal = 61,
    CFireCrackerBlast = 62,
    CFireSmoke = 63,
    CFireTrail = 64,
    CFish = 65,
    CFlashbang = 66,
    CFogController = 67,
    CFootstepControl = 68,
    CFunc_Dust = 69,
    CFunc_LOD = 70,
    CFuncAreaPortalWindow = 71,
    CFuncBrush = 72,
    CFuncConveyor = 73,
    CFuncLadder = 74,
    CFuncMonitor = 75,
    CFuncMoveLinear = 76,
    CFuncOccluder = 77,
    CFuncReflectiveGlass = 78,
    CFuncRotating = 79,
    CFuncSmokeVolume = 80,
    CFuncTrackTrain = 81,
    CGameRulesProxy = 82,
    CHandleTest = 83,
    CHEGrenade = 84,
    CHostage = 85,
    CHostageCarriableProp = 86,
    CIncendiaryGrenade = 87,
    CInferno = 88,
    CInfoLadderDismount = 89,
    CInfoOverlayAccessor = 90,
    CItem_Healthshot = 91,
    CItemDogtags = 92,
    CKnife = 93,
    CKnifeGG = 94,
    CLightGlow = 95,
    CMaterialModifyControl = 96,
    CMolotovGrenade = 97,
    CMolotovProjectile = 98,
    CMovieDisplay = 99,
    CParticleFire = 100,
    CParticlePerformanceMonitor = 101,
    CParticleSystem = 102,
    CPhysBox = 103,
    CPhysBoxMultiplayer = 104,
    CPhysicsProp = 105,
    CPhysicsPropMultiplayer = 106,
    CPhysMagnet = 107,
    CPlantedC4 = 108,
    CPlasma = 109,
    CPlayerResource = 110,
    CPointCamera = 111,
    CPointCommentaryNode = 112,
    CPointWorldText = 113,
    CPoseController = 114,
    CPostProcessController = 115,
    CPrecipitation = 116,
    CPrecipitationBlocker = 117,
    CPredictedViewModel = 118,
    CProp_Hallucination = 119,
    CPropDoorRotating = 120,
    CPropJeep = 121,
    CPropVehicleDriveable = 122,
    CRagdollManager = 123,
    CRagdollProp = 124,
    CRagdollPropAttached = 125,
    CRopeKeyframe = 126,
    CSCAR17 = 127,
    CSceneEntity = 128,
    CSensorGrenade = 129,
    CSensorGrenadeProjectile = 130,
    CShadowControl = 131,
    CSlideshowDisplay = 132,
    CSmokeGrenade = 133,
    CSmokeGrenadeProjectile = 134,
    CSmokeStack = 135,
    CSpatialEntity = 136,
    CSpotlightEnd = 137,
    CSprite = 138,
    CSpriteOriented = 139,
    CSpriteTrail = 140,
    CStatueProp = 141,
    CSteamJet = 142,
    CSun = 143,
    CSunlightShadowControl = 144,
    CTeam = 145,
    CTeamplayRoundBasedRulesProxy = 146,
    CTEArmorRicochet = 147,
    CTEBaseBeam = 148,
    CTEBeamEntPoint = 149,
    CTEBeamEnts = 150,
    CTEBeamFollow = 151,
    CTEBeamLaser = 152,
    CTEBeamPoints = 153,
    CTEBeamRing = 154,
    CTEBeamRingPoint = 155,
    CTEBeamSpline = 156,
    CTEBloodSprite = 157,
    CTEBloodStream = 158,
    CTEBreakModel = 159,
    CTEBSPDecal = 160,
    CTEBubbles = 161,
    CTEBubbleTrail = 162,
    CTEClientProjectile = 163,
    CTEDecal = 164,
    CTEDust = 165,
    CTEDynamicLight = 166,
    CTEEffectDispatch = 167,
    CTEEnergySplash = 168,
    CTEExplosion = 169,
    CTEFireBullets = 170,
    CTEFizz = 171,
    CTEFootprintDecal = 172,
    CTEFoundryHelpers = 173,
    CTEGaussExplosion = 174,
    CTEGlowSprite = 175,
    CTEImpact = 176,
    CTEKillPlayerAttachments = 177,
    CTELargeFunnel = 178,
    CTEMetalSparks = 179,
    CTEMuzzleFlash = 180,
    CTEParticleSystem = 181,
    CTEPhysicsProp = 182,
    CTEPlantBomb = 183,
    CTEPlayerAnimEvent = 184,
    CTEPlayerDecal = 185,
    CTEProjectedDecal = 186,
    CTERadioIcon = 187,
    CTEShatterSurface = 188,
    CTEShowLine = 189,
    CTesla = 190,
    CTESmoke = 191,
    CTESparks = 192,
    CTESprite = 193,
    CTESpriteSpray = 194,
    CTest_ProxyToggle_Networkable = 194,
    CTestTraceline = 196,
    CTEWorldDecal = 197,
    CTriggerPlayerMovement = 198,
    CTriggerSoundOperator = 199,
    CVGuiScreen = 200,
    CVoteController = 201,
    CWaterBullet = 202,
    CWaterLODControl = 203,
    CWeaponAug = 204,
    CWeaponAWP = 205,
    CWeaponBaseItem = 206,
    CWeaponBizon = 207,
    CWeaponCSBase = 208,
    CWeaponCSBaseGun = 209,
    CWeaponCycler = 210,
    CWeaponElite = 211,
    CWeaponFamas = 212,
    CWeaponFiveSeven = 213,
    CWeaponG3SG1 = 214,
    CWeaponGalil = 215,
    CWeaponGalilAR = 216,
    CWeaponGlock = 217,
    CWeaponHKP2000 = 218,
    CWeaponM249 = 219,
    CWeaponM3 = 220,
    CWeaponM4A1 = 221,
    CWeaponMAC10 = 222,
    CWeaponMag7 = 223,
    CWeaponMP5Navy = 224,
    CWeaponMP7 = 225,
    CWeaponMP9 = 226,
    CWeaponNegev = 227,
    CWeaponNOVA = 228,
    CWeaponP228 = 229,
    CWeaponP250 = 230,
    CWeaponP90 = 231,
    CWeaponSawedoff = 232,
    CWeaponSCAR20 = 233,
    CWeaponScout = 234,
    CWeaponSG550 = 235,
    CWeaponSG552 = 236,
    CWeaponSG556 = 237,
    CWeaponSSG08 = 238,
    CWeaponTaser = 239,
    CWeaponTec9 = 240,
    CWeaponTMP = 241,
    CWeaponUMP45 = 242,
    CWeaponUSP = 243,
    CWeaponXM1014 = 244,
    CWorld = 245,
    DustTrail = 246,
    MovieExplosion = 247,
    ParticleSmokeGrenade = 248,
    RocketTrail = 249,
    SmokeTrail = 250,
    SporeExplosion = 251,
    SporeTrail = 252
};

enum ECSPlayerBones
{
    pelvis = 0,
    spine_0,
    spine_1,
    spine_2,
    spine_3,
    neck_0,
    head_0,
    clavicle_L,
    arm_upper_L,
    arm_lower_L,
    hand_L
};

enum EntityFlags
{
    FL_ONGROUND = (1 << 0),
    FL_DUCKING = (1 << 1),
    FL_WATERJUMP = (1 << 2),
    FL_ONTRAIN = (1 << 3),
    FL_INRAIN = (1 << 4),
    FL_FROZEN = (1 << 5),
    FL_ATCONTROLS = (1 << 6),
    FL_CLIENT = (1 << 7),
    FL_FAKECLIENT = (1 << 8)
};

enum LifeState : unsigned char
{
    LIFE_ALIVE = 0,// alive
    LIFE_DYING = 1, // playing death animation or still falling off of a ledge waiting to hit ground
    LIFE_DEAD = 2 // dead. lying still.
};

enum WeaponSound_t
{
    EMPTY,
    SINGLE,
    SINGLE_NPC,
    WPN_DOUBLE, // Can't be "DOUBLE" because windows.h uses it.
    DOUBLE_NPC,
    BURST,
    RELOAD,
    RELOAD_NPC,
    MELEE_MISS,
    MELEE_HIT,
    MELEE_HIT_WORLD,
    SPECIAL1,
    SPECIAL2,
    SPECIAL3,
    TAUNT,
    FAST_RELOAD,

    // Add new shoot sound types here
    REVERSE_THE_NEW_SOUND,

    NUM_SHOOT_SOUND_TYPES,
};

enum MoveType_t
{
    MOVETYPE_NONE = 0,
    MOVETYPE_ISOMETRIC,
    MOVETYPE_WALK,
    MOVETYPE_STEP,
    MOVETYPE_FLY,
    MOVETYPE_FLYGRAVITY,
    MOVETYPE_VPHYSICS,
    MOVETYPE_PUSH,
    MOVETYPE_NOCLIP,
    MOVETYPE_LADDER,
    MOVETYPE_OBSERVER,
    MOVETYPE_CUSTOM,
    MOVETYPE_LAST = MOVETYPE_CUSTOM,
    MOVETYPE_MAX_BITS = 4
};